"use client";

import { useState } from "react";
import { ArrowRight, Film, FolderKanban, Pencil, Plus, Search, Trash2, X } from "lucide-react";

export type WorkshopProject = {
  number: string; title: string; busy?: boolean; phase?: string; message?: string; source?: string;
  mp4?: string; updated_at?: string; created_at?: string; category?: string; memo?: string;
  work_complete?: boolean; uploaded?: boolean; narration_ready?: boolean;
};
export type ProjectCommand = { action: "open" | "new" | "update" | "delete"; number?: string; title?: string; category?: string; memo?: string; work_complete?: boolean; uploaded?: boolean };
const field = "mt-1.5 w-full rounded-xl border border-border bg-white p-3 text-sm";
function progress(p: WorkshopProject) { return p.uploaded ? 100 : p.work_complete || p.mp4 ? 90 : p.phase === "planned" || p.narration_ready ? 60 : p.source ? 25 : 0; }
function bucket(p: WorkshopProject) { return p.uploaded ? "uploaded" : (p.work_complete ?? !!p.mp4) ? "complete" : "active"; }

export default function ProjectDashboard({ projects, ready, busy, saving, error, command }: {
  projects: (WorkshopProject & { narration_ready?: boolean })[]; ready: boolean; busy: boolean; saving: boolean; error: string;
  command: (value: ProjectCommand) => Promise<void>;
}) {
  const [query, setQuery] = useState("");
  const [view, setView] = useState("active");
  const [sort, setSort] = useState("updated");
  const [ascending, setAscending] = useState(false);
  const [editing, setEditing] = useState<WorkshopProject | null>(null);
  const filtered = projects.filter(p => bucket(p) === view && `${p.title} ${p.category || ""}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).sort((a, b) => {
    const value = sort === "name" ? a.title.localeCompare(b.title, "ko") : sort === "progress" ? progress(a) - progress(b) : (a.updated_at || a.created_at || "").localeCompare(b.updated_at || b.created_at || "");
    return ascending ? value : -value;
  });
  const groups = Map.groupBy(filtered, p => p.category?.trim() || "미분류");
  const disabled = !ready || saving;
  const run = (value: ProjectCommand) => { void command(value).catch(() => {}); };
  return <div className="mx-auto max-w-6xl space-y-6">
    <section className="rounded-3xl border border-border bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><span className="inline-flex items-center gap-2 rounded-full bg-brand-cream px-3 py-1.5 text-xs font-bold text-brand-olive"><Film size={14} />독백(가족)</span><h1 className="mt-3 text-3xl font-bold">독백 제작 스튜디오</h1><p className="mt-2 text-sm text-muted-foreground">원본부터 영상 출력까지 프로젝트별 제작 흐름을 이어서 관리합니다.</p></div><button disabled={disabled || busy} onClick={() => run({action: "new"})} className="inline-flex items-center gap-2 rounded-xl bg-brand-olive px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><Plus size={16} />새 프로젝트</button></div></section>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}
    <div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><Search size={17} className="absolute left-3.5 top-3.5 text-muted-foreground" /><input aria-label="프로젝트 또는 카테고리 검색" placeholder="프로젝트 또는 카테고리 검색" value={query} onChange={e => setQuery(e.target.value)} className="h-11 w-full rounded-xl border border-border bg-white pl-10 pr-4 text-sm" /></label><div className="grid grid-cols-3 rounded-xl border border-border bg-white p-1">{[["active", "진행 중"], ["complete", "작업 완료"], ["uploaded", "업로드 완료"]].map(([key, label]) => <button key={key} onClick={() => setView(key)} className={`rounded-lg px-3 py-2 text-sm font-bold ${view === key ? "bg-brand-olive text-white" : "text-muted-foreground"}`}>{label} <small>{projects.filter(p => bucket(p) === key).length}</small></button>)}</div></div>
    <div className="flex justify-end gap-2">{[["progress", "진행도순"], ["name", "이름순"], ["updated", "수정순"]].map(([key, label]) => <button key={key} onClick={() => { setSort(key); setAscending(sort === key ? !ascending : key === "name"); }} className={`rounded-lg border px-3 py-2 text-xs font-bold ${sort === key ? "border-brand-olive bg-brand-cream" : "border-border bg-white"}`}>{label}{sort === key && (ascending ? " ↑" : " ↓")}</button>)}</div>
    {!ready ? <p role="status" className="rounded-2xl border border-border bg-white p-12 text-center">제작실의 프로젝트 목록을 불러오는 중…</p> : !filtered.length ? <div className="rounded-2xl border border-dashed border-border bg-white p-12 text-center"><FolderKanban className="mx-auto text-muted-foreground" /><p className="mt-3 font-bold">표시할 프로젝트가 없습니다</p><p className="mt-1 text-sm text-muted-foreground">새 프로젝트를 만들거나 검색어와 상태를 확인해 주세요.</p></div> : [...groups.entries()].sort(([a], [b]) => a === "미분류" ? 1 : b === "미분류" ? -1 : a.localeCompare(b, "ko")).map(([category, rows]) => <section key={category}><h2 className="mb-3 flex items-center gap-2 font-bold"><FolderKanban size={17} />{category}<small className="text-muted-foreground">{rows.length}</small></h2><div className="grid gap-3 md:grid-cols-3">{rows.map(p => <article key={p.number} className="rounded-2xl border border-border bg-white p-4 shadow-sm hover:border-brand-olive/40"><div className="flex items-start gap-2"><button onClick={() => run({action: "open", number: p.number})} disabled={saving} className="min-w-0 flex-1 text-left"><span className="rounded-full bg-brand-cream px-2.5 py-1 text-xs font-bold text-brand-olive-dark">{p.category || "미분류"}</span><h3 className="mt-3 truncate font-bold">{p.title || p.number}</h3><p className="mt-2 text-xs text-muted-foreground">{p.updated_at || p.created_at || "최근 수정 기록 없음"}</p></button><button aria-label={`${p.title} 수정`} disabled={disabled || p.busy} title={p.busy ? "이 프로젝트의 작업이 끝난 뒤 수정할 수 있습니다." : "프로젝트 수정"} onClick={() => setEditing({...p, work_complete: bucket(p) !== "active"})} className="rounded-lg p-2 text-muted-foreground hover:bg-brand-cream disabled:opacity-40"><Pencil size={14} /></button><button aria-label={`${p.title} 삭제`} disabled={disabled || p.busy} title={p.busy ? "이 프로젝트의 작업이 끝난 뒤 삭제할 수 있습니다." : "프로젝트 삭제"} onClick={() => { if (window.confirm(`‘${p.title}’ 프로젝트를 목록에서 삭제할까요? 원본과 결과물은 폴더에 보관됩니다.`)) run({action: "delete", number: p.number}); }} className="rounded-lg p-2 text-muted-foreground hover:bg-red-50 hover:text-red-600 disabled:opacity-40"><Trash2 size={14} /></button></div><button onClick={() => run({action: "open", number: p.number})} className="mt-4 block w-full text-left"><div className="mb-2 flex justify-between text-xs"><span>{p.uploaded ? "업로드 완료" : bucket(p) === "complete" ? "작업 완료" : p.message || "시작 전"}</span><b>{progress(p)}%</b></div><div className="flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full bg-brand-olive" style={{width: `${progress(p)}%`}} /></div><ArrowRight size={15} /></div></button></article>)}</div></section>)}
    {editing && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/45 p-4"><form role="dialog" aria-modal="true" aria-label="프로젝트 편집" onSubmit={async e => {e.preventDefault(); try {await command({action: "update", number: editing.number, title: editing.title, category: editing.category || "", memo: editing.memo || "", work_complete: !!editing.work_complete, uploaded: !!editing.uploaded}); setEditing(null);} catch { /* Keep the draft for retry. */ } }} className="max-h-[92vh] w-full max-w-md space-y-4 overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="font-bold">프로젝트 편집</h2><button type="button" aria-label="닫기" disabled={saving} onClick={() => setEditing(null)}><X size={18} /></button></div>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}<label className="block text-xs font-bold">카테고리<input className={field} value={editing.category || ""} onChange={e => setEditing({...editing, category: e.target.value})} /></label><label className="block text-xs font-bold">제목 *<input required maxLength={60} className={field} value={editing.title} onChange={e => setEditing({...editing, title: e.target.value})} /></label><div className="flex gap-4"><label><input type="checkbox" checked={!!editing.work_complete} onChange={e => setEditing({...editing, work_complete: e.target.checked, uploaded: e.target.checked && editing.uploaded})} /> 작업 완료</label><label><input type="checkbox" checked={!!editing.uploaded} onChange={e => setEditing({...editing, uploaded: e.target.checked, work_complete: e.target.checked || editing.work_complete})} /> 업로드 완료</label></div><label className="block text-xs font-bold">메모<textarea className={field} value={editing.memo || ""} onChange={e => setEditing({...editing, memo: e.target.value})} /></label><p className="break-all text-xs text-muted-foreground">프로젝트 경로: {editing.number}</p><div className="flex gap-3"><button type="button" disabled={saving} onClick={() => setEditing(null)} className="flex-1 rounded-xl bg-muted p-3">취소</button><button disabled={disabled} className="flex-1 rounded-xl bg-brand-olive p-3 font-bold text-white disabled:opacity-50">{saving ? "저장 중…" : "저장하기"}</button></div></form></div>}
  </div>;
}
