-- 개인용 가족 쇼츠 급상승 추적: 영상 원장, 시간별 통계 스냅샷, 사용자 전역 제외 상태

create table if not exists public.shorts_family_hot_videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id text not null,
  url text not null,
  title text not null default '',
  channel_id text not null default '',
  channel_name text not null default '',
  country text not null default 'ALL' check (country in ('ALL', 'KR', 'JP', 'US')),
  category text not null default '가족',
  thumbnail_url text not null default '',
  published_at timestamptz not null,
  duration_seconds integer not null default 0,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  latest_view_count bigint not null default 0,
  latest_like_count bigint not null default 0,
  latest_comment_count bigint not null default 0,
  dismissed_at timestamptz,
  dismissed_reason text not null default '',
  saved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, video_id)
);

create table if not exists public.shorts_family_hot_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  hot_video_id uuid not null references public.shorts_family_hot_videos(id) on delete cascade,
  captured_at timestamptz not null default now(),
  view_count bigint not null default 0,
  like_count bigint not null default 0,
  comment_count bigint not null default 0
);

create index if not exists shorts_family_hot_videos_user_active_idx
  on public.shorts_family_hot_videos(user_id, dismissed_at, published_at desc);

create index if not exists shorts_family_hot_snapshots_video_time_idx
  on public.shorts_family_hot_snapshots(hot_video_id, captured_at desc);

alter table public.shorts_family_hot_videos enable row level security;
alter table public.shorts_family_hot_snapshots enable row level security;

drop policy if exists "Users manage own family hot videos" on public.shorts_family_hot_videos;
create policy "Users manage own family hot videos" on public.shorts_family_hot_videos
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users manage own family hot snapshots" on public.shorts_family_hot_snapshots;
create policy "Users manage own family hot snapshots" on public.shorts_family_hot_snapshots
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

