import React,{useLayoutEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {treeRows} from './taskGraph.js';
import {getDaysBetween} from './utils.js';
import GanttRowMenu from './GanttRowMenu.jsx';
export default function GanttTasks({data,filtered,project,visibleProjects,onReorder,collapsed,setCollapsed,range,days,zoom,datesFor,drag,beginDrag,moveDrag,finishDrag,setDrag,edit,addTaskTo,copyTask,deleteTask,editProject,copyProject,deleteProject,selected,setSelected,link,setLink,onLink,onUnlink}) {
  const root=useRef(null),[paths,setPaths]=useState([]),[hover,setHover]=useState(null);
  const projects=(visibleProjects||data.projects).filter(p=>!project||p.id===project);
  const moving=useRef(null);
  const drop=(e,kind,id)=>{e.preventDefault();if(moving.current?.kind===kind)onReorder(kind,moving.current.id,id);moving.current=null;};
  const handle=(kind,item)=><button className="row-grip" aria-label={`${item.name||item.title} 순서 변경`} draggable onDragStart={e=>{e.stopPropagation();moving.current={kind,id:item.id};e.dataTransfer.setData('text/plain',item.id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>moving.current=null} onPointerDown={e=>e.stopPropagation()}>⠿</button>;
  useLayoutEffect(()=>{
    const update=()=>{if(!root.current)return;const bounds=root.current.getBoundingClientRect(),positions=new Map();
      for(const el of root.current.querySelectorAll('[data-task-bar]')){const b=el.getBoundingClientRect();positions.set(el.dataset.taskBar,{x:b.x-bounds.x-240,y:b.y-bounds.y+b.height/2,w:b.width});}
      const next=[];for(const task of data.tasks){const to=positions.get(task.id);if(!to)continue;for(const id of task.predecessors||[]){const from=positions.get(id);if(!from)continue;const x=from.x+from.w,y=from.y;const elbow=x+15;next.push({from:id,to:task.id,d:`M ${x} ${y} H ${elbow} V ${to.y} H ${to.x-4}`,label:`${data.tasks.find(t=>t.id===id)?.title} → ${task.title}`});}}setPaths(next);};
    update();const observer=new ResizeObserver(update);observer.observe(root.current);return()=>observer.disconnect();
  },[data.tasks,data.projects,data.phases,data.works,filtered,collapsed,range,days,zoom,drag,project]);
  const pick=t=>{if(link){onLink(link.direction==='after'?link.id:t.id,link.direction==='after'?t.id:link.id);return;}setSelected(t.id);};
  const hoverTask=(e,t)=>{const b=e.currentTarget.getBoundingClientRect();setHover({id:t.id,x:Math.min(window.innerWidth-290,Math.max(8,b.left)),y:b.top>170?b.top-150:b.bottom+12});};
  const current=hover&&data.tasks.find(t=>t.id===hover.id);
  return <div className="gantt-task-groups" ref={root} onMouseLeave={()=>setHover(null)}>
    <svg className="dependency-lines" style={{width:days*zoom}} aria-label="작업 연결선"><defs><marker id="dependency-arrow" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 L6 3 L0 6" fill="#a9b8d6"/></marker></defs>{paths.map(p=><path key={p.from+p.to} d={p.d} fill="none" stroke="#a9b8d6" strokeWidth="1.5" markerEnd="url(#dependency-arrow)" onDoubleClick={()=>onUnlink(p.from,p.to)}><title>{p.label}</title></path>)}</svg>
    {data.phases.filter(ph=>projects.some(p=>p.phaseId===ph.id)).map(ph=><React.Fragment key={ph.id}><div className="gantt-project hierarchy-phase"><div className="gantt-label"><button className="gantt-collapse" onClick={()=>setCollapsed(c=>({...c,[ph.id]:!c[ph.id]}))}>{collapsed[ph.id]?'▶':'▼'}</button><span><span className="phase-work-icon" aria-label={data.works.find(w=>w.id===ph.workId)?.name}>{/영상|video/i.test(data.works.find(w=>w.id===ph.workId)?.name||'')?'🎬':/코딩|개발|coding|code/i.test(data.works.find(w=>w.id===ph.workId)?.name||'')?'💻':'📁'}</span> {ph.name}</span></div><div className="project-track"/></div>{!collapsed[ph.id]&&projects.filter(p=>p.phaseId===ph.id).map(p=><React.Fragment key={p.id}><div className="gantt-project" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,'projects',p.id)}><div className="gantt-label">{handle('projects',p)}<button className="gantt-collapse" aria-label={`${p.name} ${collapsed[p.id]?'펼치기':'접기'}`} aria-expanded={!collapsed[p.id]} onClick={()=>setCollapsed(c=>({...c,[p.id]:!c[p.id]}))}>{collapsed[p.id]?'▶':'▼'}</button><i style={{background:p.color}}/><span className="gantt-row-name">{p.name}</span><GanttRowMenu onEdit={()=>editProject(p)} name={p.name} addLabel="하위 작업 추가" onAdd={()=>addTaskTo(p.id)} onCopy={()=>copyProject(p)} onDelete={()=>deleteProject(p)} deleteDisabled={data.projects.length===1}/></div><div className="project-track"/></div>
    {!collapsed[p.id]&&treeRows(data.tasks.filter(t=>t.projectId===p.id),filtered.filter(t=>t.projectId===p.id),collapsed).map(({task:original,depth,hasChildren})=>{const t=datesFor(original);const left=getDaysBetween(range,t.start)*zoom,width=(getDaysBetween(t.start,t.end)+1)*zoom;
      return <div className={`gantt-row ${selected===t.id?'selected-task-row':''}`} key={t.id} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,'tasks',t.id)}><div className="gantt-label task-row-label" style={{paddingLeft:10+depth*15}}>{handle('tasks',t)}{hasChildren?<button className="gantt-collapse" aria-label={`${t.title} ${collapsed[t.id]?'펼치기':'접기'}`} onClick={()=>setCollapsed(c=>({...c,[t.id]:!c[t.id]}))}>{collapsed[t.id]?'▶':'▼'}</button>:<span className="tree-indent"/>}<button className="gantt-row-name task-name-button" onClick={()=>pick(t)} onDoubleClick={()=>!link&&edit(original)}>{t.title}<small>{data.phases.find(x=>x.id===t.phaseId)?.name||''}</small></button><GanttRowMenu onEdit={()=>edit(original)} name={t.title} addLabel="하위 작업 추가" onAdd={()=>addTaskTo(t.projectId,t.id)} onCopy={()=>copyTask(original)} onDelete={()=>deleteTask(t.id)}/></div>
      <div className="track task-timeline" style={{backgroundSize:`${zoom}px 100%`}}><div className="task-bar-wrap" data-task-id={t.id} data-task-bar={t.id} style={{left,width}} onMouseEnter={e=>hoverTask(e,t)} onMouseLeave={()=>setHover(null)}>
        <div className={`gantt-bar ${t.status} ${selected===t.id?'selected':''}`} role="button" tabIndex={0} aria-label={`${t.title} 선택`} style={{background:t.status==='done'?'#398f7d':p.color}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();edit(original);}if(e.key===' '){e.preventDefault();pick(t);}}} onPointerDown={e=>{if(link){e.stopPropagation();return;}beginDrag(e,original,'move');}} onPointerMove={moveDrag} onPointerUp={e=>{if(link){e.stopPropagation();pick(t);}else finishDrag(e);}} onPointerCancel={()=>setDrag(null)} onDoubleClick={()=>{if(!link&&!drag)edit(original);}}>
          <span className="resize left" aria-label="시작일 조절" onPointerDown={e=>{if(!link)beginDrag(e,original,'start');}}>│</span><span className="bar-text">{t.title}</span><span className="resize right" aria-label="마감일 조절" onPointerDown={e=>{if(!link)beginDrag(e,original,'end');}}>│</span>
        </div>
        <button className="dependency-node before" aria-label={`${t.title} 선행 연결`} onPointerDown={e=>e.stopPropagation()} onClick={()=>{setLink({id:t.id,direction:'before'});setHover(null);}}>←</button><button className="dependency-node after" aria-label={`${t.title} 후행 연결`} onPointerDown={e=>e.stopPropagation()} onClick={()=>{setLink({id:t.id,direction:'after'});setHover(null);}}>→</button>
      </div></div></div>;
    })}</React.Fragment>)}</React.Fragment>)}
    {current&&!drag&&!link&&createPortal(<div className="task-hover-info" role="tooltip" style={{left:hover.x,top:hover.y}}><strong>{current.title}</strong><span>{data.projects.find(p=>p.id===current.projectId)?.name} {data.phases.find(p=>p.id===current.phaseId)?.name}</span><span>{current.start} → {current.end}</span><span>{{waiting:'작업대기',progress:'작업중',done:'작업완료'}[current.status]}</span></div>,document.body)}
  </div>;
}
