import React,{useState} from 'react';
import {today,addDays} from './scheduler.js';
import {getDaysBetween,parseDate,formatDate} from './utils.js';
import {isDue} from './recurrence.js';
export default function MonthlyScheduler({data,tasks,query,onAdd,onEdit,onMove,commit}){
 const [month,setMonth]=useState(today().slice(0,7)),[over,setOver]=useState(null),[showRoutines,setShowRoutines]=useState(true);
 const first=month+'-01',start=addDays(first,-parseDate(first).getDay());
 const dates=Array.from({length:42},(_,i)=>addDays(start,i));
 const shift=n=>{const d=parseDate(first);d.setMonth(d.getMonth()+n);setMonth(formatDate(d).slice(0,7));};
 const toggle=(r,date)=>commit({...data,routines:data.routines.map(x=>x.id===r.id?{...x,checks:{...x.checks,[date]:!x.checks[date]}}:x)});
 return <section className="monthly-scheduler" aria-label="월간 스케줄러"><div className="calendar-tools"><button aria-label="이전 달" onClick={()=>shift(-1)}>‹</button><button onClick={()=>setMonth(today().slice(0,7))}>오늘</button><button aria-label="다음 달" onClick={()=>shift(1)}>›</button><input aria-label="표시 월" type="month" value={month} onChange={e=>/^\d{4}-\d{2}$/.test(e.target.value)&&setMonth(e.target.value)}/><label><input type="checkbox" checked={showRoutines} onChange={e=>setShowRoutines(e.target.checked)}/>루틴 표시</label></div><div className="calendar-scroll"><div className="calendar-grid">{'일월화수목금토'.split('').map((day,i)=><div className={`calendar-weekday day-${i}`} key={day}>{day}</div>)}{dates.map((date,i)=><div key={date} data-calendar-date={date} className={`calendar-day ${date.slice(0,7)!==month?'outside':''} ${date===today()?'is-today':''} ${over===date?'drop-target':''}`} onDragOver={e=>{if(e.dataTransfer.types.includes('application/planner-task')){e.preventDefault();setOver(date);}}} onDragLeave={()=>setOver(null)} onDrop={e=>{e.preventDefault();setOver(null);try{const item=JSON.parse(e.dataTransfer.getData('application/planner-task'));const task=tasks.find(t=>t.id===item.id);if(task&&dates.includes(item.date))onMove(task.id,{start:addDays(task.start,getDaysBetween(item.date,date)),end:addDays(task.end,getDaysBetween(item.date,date))});}catch{}}}><div className="calendar-date"><span className={`day-${i%7}`}>{Number(date.slice(8))}</span><button aria-label={`${date} 일정 추가`} onClick={()=>onAdd(date)}>＋</button></div><div className="calendar-events">{tasks.filter(t=>t.start<=date&&t.end>=date).map(t=><button key={t.id} className={`calendar-event ${t.status==='done'?'completed':''}`} style={{borderLeftColor:data.projects.find(p=>p.id===t.projectId)?.color||'#9684ff'}} title={`${t.title} · ${t.start} ~ ${t.end}`} aria-label={`${date} ${t.title} 수정`} draggable onDragStart={e=>{e.dataTransfer.setData('application/planner-task',JSON.stringify({id:t.id,date}));e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>setOver(null)} onClick={()=>onEdit(t)}>{t.status==='done'?'✓ ':''}{t.title}</button>)}{showRoutines&&(data.routines||[]).filter(r=>isDue(r,date)&&r.title.toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.id} className={`calendar-routine ${r.checks[date]?'completed':''}`} aria-label={`${date} ${r.title} 완료`} aria-pressed={!!r.checks[date]} onClick={()=>toggle(r,date)}>{r.checks[date]?'✓':'○'} {r.title}</button>)}</div></div>)}</div></div></section>;
}
