import test from 'node:test';
import assert from 'node:assert/strict';
import { schedule, addDays, validateData } from './scheduler.js';
const settings={start:'2026-09-28',deadline:'2026-10-02',hours:6,weekdays:[1,2,3,4,5]};
const task=(id,extra={})=>({id,title:id,projectId:'p',phaseId:'',status:'waiting',start:'2026-09-28',end:'2026-09-28',hours:6,priority:2,deadline:'',locked:false,...extra});
test('capacity is shared across tasks, skipping weekends',()=>{const r=schedule([task('a',{hours:8}),task('b',{hours:28})],settings);assert.equal(r[0].end,'2026-09-29');assert.equal(r[1].end,'2026-10-05');assert.equal(r[1].delay,3);const used={};r.flatMap(t=>t.allocations).forEach(a=>used[a.date]=(used[a.date]||0)+a.hours);assert.ok(Object.values(used).every(h=>h<=6));assert.equal(used['2026-10-03'],undefined);});
test('locked tasks and other projects reserve time; done tasks do not',()=>{const r=schedule([task('fixed',{locked:true}),task('other',{projectId:'q',start:'2026-09-29',end:'2026-09-29'}),task('done',{status:'done'}),task('new')],settings,'p');assert.equal(r.length,1);assert.equal(r[0].start,'2026-09-30');});
test('earliest due date then priority; earliest start respected',()=>{const r=schedule([task('low',{priority:1}),task('high',{priority:3}),task('due',{deadline:'2026-09-28'}),task('future',{start:'2026-10-08'})],settings);assert.deepEqual(r.map(t=>t.id),['due','high','future','low']);assert.equal(r[2].start,'2026-10-08');});
test('invalid working calendar rejected; quarter hours supported',()=>{assert.throws(()=>schedule([task('x')],{...settings,weekdays:[]}));const r=schedule([task('x',{hours:.25}),task('y',{hours:5.75})],settings);assert.equal(r[1].end,settings.start);});
test('month/year and leap date boundaries',()=>{assert.equal(addDays('2026-12-31',1),'2027-01-01');assert.equal(addDays('2028-02-28',1),'2028-02-29');});
test('backup validation checks references and dates',()=>{const data={version:1,projects:[{id:'p',name:'Project'}],phases:[],tasks:[task('a')],settings};assert.equal(validateData(data),data);assert.throws(()=>validateData({...data,tasks:[task('a',{projectId:'missing'})]}));assert.throws(()=>validateData({...data,tasks:[task('a',{start:'2026-02-30'})]}));});
test('legacy backups remain compatible; routine history and matrix are validated',()=>{const data={version:1,projects:[{id:'p',name:'Project'}],phases:[],tasks:[],settings};assert.equal(validateData(data),data);const updated={...data,routines:[{id:'r',kind:'weekly',title:'Review',checks:{'2026-09-28':true}}],matrix:{q1:'Upload',q2:''}};assert.equal(validateData(updated),updated);assert.throws(()=>validateData({...updated,routines:[{...updated.routines[0],checks:{'2026-09-29':true}}]}));assert.throws(()=>validateData({...updated,matrix:{q1:42}}));});

